/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SocialWorker;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author shiva
 */
public class SocialWorkerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SocialWorkerWorkAreaJPanel
     */
   public JPanel userProcessContainer;
    
    public UserAccount account;
    
    public EcoSystem system;
    public SocialWorkerWorkAreaJPanel(JPanel container, UserAccount account, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = container;
        this.account = account;
        this.system = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AssignChildtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Assignchildbtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AssignChildtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(AssignChildtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 93));

        jLabel1.setText("Assigning Child to Parent");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        Assignchildbtn.setText("Assign Child");
        add(Assignchildbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AssignChildtable;
    private javax.swing.JButton Assignchildbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
