/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SysAdminRole;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FosterCareEnterprise;
import Business.EnterpriseAdmin.EnterpriseAdmin;
import Business.Network.Network;
import Business.Role.FosterCareCenterEnterpriseAdmin;
import Business.Role.FundRaiserEnterpriseAdmin;
import Business.Role.RentalEnterPriseAdminRole;
import Business.Role.SystemAdminRole;
import Business.Role.TrainingCenterEnterPriseAdmin;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import sun.security.util.Password;

/**
 *
 * @author koushik
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    private JPanel userProcessContainer;
    public EcoSystem system;
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        populateTable();
        populateNetworkComboBox();
    }
    
    private void populateNetworkComboBox() {
        comboNetwork.removeAllItems();
        cbEnterpriseName.removeAllItems();

        for (Network network : system.getNetworkList()) {
            comboNetwork.addItem(network);
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterpriseAdmin.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollpaneEnterpriseAdmin = new javax.swing.JScrollPane();
        tblEnterpriseAdmin = new javax.swing.JTable();
        lblNetwork = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        cbNetwork = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();
        cbEnterpriseName = new javax.swing.JComboBox();
        lblEmail = new javax.swing.JLabel();
        deleteAdmin = new javax.swing.JButton();
        txtName1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblTitle.setText("Manage Enterprise Admin");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        scrollpaneEnterpriseAdmin.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N

        tblEnterpriseAdmin.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        tblEnterpriseAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneEnterpriseAdmin.setViewportView(tblEnterpriseAdmin);

        add(scrollpaneEnterpriseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 570, 210));

        lblNetwork.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblNetwork.setText("Network:");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        lblEnterpriseType.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblEnterpriseType.setText("Enterprise Type:");
        add(lblEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, -1, -1));

        lblUsername.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));

        lblPassword.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 170, 30));

        btnBack.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel1.setText("Phone:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        txtPhone.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 170, 30));

        txtUsername.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 170, 30));

        pwdPassword.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 170, 30));

        cbNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SysAdminRole/children.png"))); // NOI18N
        add(cbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 740, 270));

        comboNetwork.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        comboNetwork.setForeground(new java.awt.Color(25, 56, 82));
        comboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 170, -1));

        cbEnterpriseName.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        cbEnterpriseName.setForeground(new java.awt.Color(25, 56, 82));
        cbEnterpriseName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterpriseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterpriseNameActionPerformed(evt);
            }
        });
        add(cbEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 170, -1));

        lblEmail.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblEmail.setText("Email: ");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 50, 20));

        deleteAdmin.setText("DeleteAdmin");
        deleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdminActionPerformed(evt);
            }
        });
        add(deleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        txtName1.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
//        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
      Enterprise enterprise = (Enterprise) cbEnterpriseName.getSelectedItem();
        String username = txtUsername.getText();
        String password = String.valueOf(pwdPassword.getPassword());
        String name = txtEmail.getText();
        String Phone = txtPhone.getText();
        String Email = txtEmail.getText();
        
        if (username.isEmpty() || password.isEmpty() || name.isEmpty()
                || cbEnterpriseName.getSelectedItem() == null || comboNetwork.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!system.checkValidPasswordFormat(password)) {
            return;
        }
        if (!system.checkIfUserIsUnique(username)) {
            return;
        }
        EnterpriseAdmin admin = new EnterpriseAdmin(name, Phone, Email);
        admin.setNetwork((Network)comboNetwork.getSelectedItem());
        admin.setEnterprise((Enterprise)cbEnterpriseName.getSelectedItem());
        
         Enterprise e = (Enterprise)cbEnterpriseName.getSelectedItem();
         e.setAdmin(admin);
        
        Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
        UserAccount account = null;
        if (null != enterprise.getEnterpriseType()) {
            switch (enterprise.getEnterpriseType()) {
                case FosterCare:
                    
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new FosterCareCenterEnterpriseAdmin());
                    break;
                case FundRaiser:
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new FundRaiserEnterpriseAdmin());
                    break;
                case Rental:
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new RentalEnterPriseAdminRole());
                    break;
                case TrainingCenter:
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new TrainingCenterEnterPriseAdmin());
                    break;
                default:
                    break;
            }
        }
        txtUsername.setText("");
        pwdPassword.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        JOptionPane.showMessageDialog(null, "User Account created sucessfully");
       populateTable();
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed

        Network network = (Network) comboNetwork.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_comboNetworkActionPerformed

     private void populateEnterpriseComboBox(Network network) {
        cbEnterpriseName.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            cbEnterpriseName.addItem(enterprise);
        }

    }
    
    private void cbEnterpriseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterpriseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEnterpriseNameActionPerformed

    private void deleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAdminActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblEnterpriseAdmin.getSelectedRow();
        if(selectedrow >= 0){
            DefaultTableModel tableRecords = (DefaultTableModel)tblEnterpriseAdmin.getModel();
            String username = (String)tableRecords.getValueAt(selectedrow, 2);
            
            for (Network network : system.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    UserAccount ua = null;
                    for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                        if(userAccount.getUsername().equals(username)){
                            ua = userAccount;
                            break;
                        }
                    }
                    enterprise.getUserAccountDirectory().getUserAccountList().remove(ua);
                    break;
            }
            JOptionPane.showMessageDialog(null, "Enterprise Admin deleted.");
            populateTable();
        }
        }
    }//GEN-LAST:event_deleteAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbEnterpriseName;
    private javax.swing.JLabel cbNetwork;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JButton deleteAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JScrollPane scrollpaneEnterpriseAdmin;
    private javax.swing.JTable tblEnterpriseAdmin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
