/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrationRole;

/**
 *
 * @author koushik
 */
public class FosterEntManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterEntManageUserAccountJPanel
     */
    public FosterEntManageUserAccountJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollpaneUsersTable = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        lblOrganization = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        cbOrganization = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        txtPhone = new javax.swing.JTextField();
        scrollpaneAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("Manage Foster Center User Accounts");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneUsersTable.setViewportView(tblUsers);

        add(scrollpaneUsersTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 550, 230));

        lblOrganization.setText("Organization:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        lblRole.setText("Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        lblPhone.setText("Phone:");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        btnCreateUser.setText("Create User");
        add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 760, -1, -1));

        lblAddress.setText("Address:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, -1, -1));

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Children", "Parent", "Social Worker", " " }));
        add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 200, -1));

        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Children", "Parent", "Social Worker", " " }));
        add(cbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 200, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 200, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 200, -1));
        add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 200, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 200, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        scrollpaneAddress.setViewportView(txtAddress);

        add(scrollpaneAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> cbOrganization;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JScrollPane scrollpaneAddress;
    private javax.swing.JScrollPane scrollpaneUsersTable;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
