/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrationRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author shiva
 */
public class FosterEntAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterEntAdminWorkAreaPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
    Organization organization;
    
    public FosterEntAdminWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FosterSplit = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageOrg = new javax.swing.JButton();
        btnManageEmp = new javax.swing.JButton();
        btnManageReq = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        FosterSplit.setDividerLocation(200);

        jPanel1.setBackground(new java.awt.Color(255, 229, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageOrg.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.setMinimumSize(new java.awt.Dimension(137, 23));
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 170, -1));

        btnManageEmp.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnManageEmp.setText("Manage Employee");
        btnManageEmp.setMaximumSize(new java.awt.Dimension(135, 23));
        btnManageEmp.setMinimumSize(new java.awt.Dimension(137, 23));
        btnManageEmp.setPreferredSize(new java.awt.Dimension(135, 23));
        btnManageEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        btnManageReq.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnManageReq.setText("Manage Requests");
        btnManageReq.setMaximumSize(new java.awt.Dimension(135, 23));
        btnManageReq.setMinimumSize(new java.awt.Dimension(137, 23));
        btnManageReq.setPreferredSize(new java.awt.Dimension(135, 23));
        btnManageReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReqActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        FosterSplit.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 229, 180));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        FosterSplit.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FosterSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FosterSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:
        FosterEntManageOrganizationJPanel fosterorg=new FosterEntManageOrganizationJPanel(enterprise.getOrganizationDirectory());
        FosterSplit.setRightComponent(fosterorg);
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnManageEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmpActionPerformed
        // TODO add your handling code here:
        FosterEntManageEmpJPanel fosteremp=new FosterEntManageEmpJPanel(enterprise,organization,enterprise.getOrganizationDirectory());
        FosterSplit.setRightComponent(fosteremp);
    }//GEN-LAST:event_btnManageEmpActionPerformed

    private void btnManageReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReqActionPerformed
        // TODO add your handling code here:
        FosterEntManageRequestJPanel fosterreq=new FosterEntManageRequestJPanel();
        FosterSplit.setRightComponent(fosterreq);
    }//GEN-LAST:event_btnManageReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane FosterSplit;
    private javax.swing.JButton btnManageEmp;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManageReq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
