/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrationRole;

/**
 *
 * @author koushik
 */
public class FundRaiserEntManageUserAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FundRaiserEntManageUserAccJPanel
     */
    public FundRaiserEntManageUserAccJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollpaneUsersTable = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        lblOrganization = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        cbOrganization = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        txtPhone = new javax.swing.JTextField();
        scrollpaneAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 229, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblTitle.setText("Manage Fundraiser Enterprise User Accounts");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneUsersTable.setViewportView(tblUsers);

        add(scrollpaneUsersTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 550, 100));

        lblOrganization.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblOrganization.setText("Organization:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        lblRole.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblRole.setText("Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        lblUsername.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        lblPassword.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        lblPhone.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblPhone.setText("Phone:");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        btnCreateUser.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, -1, -1));

        lblAddress.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        lblAddress.setText("Address:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        cbRole.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Treasurer", "NGO" }));
        add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 200, -1));

        cbOrganization.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Treasurer", "NGO" }));
        add(cbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 200, -1));

        txtUsername.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 200, -1));

        txtName.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 200, -1));

        pwdPassword.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 200, -1));

        txtPhone.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 200, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        scrollpaneAddress.setViewportView(txtAddress);

        add(scrollpaneAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SysAdminRole/children.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 740, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> cbOrganization;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JScrollPane scrollpaneAddress;
    private javax.swing.JScrollPane scrollpaneUsersTable;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
