/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrationRole;

import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author koushik
 */
public class RentalEntManageOrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentalEntManageOrgJPanel
     */
    private final OrganizationDirectory directory;
    public RentalEntManageOrgJPanel(OrganizationDirectory directory) {
        initComponents();
         this.directory = directory;
        volPopulate();
        populateOrganizationTypeComboBox();
    }
    
    public void volPopulate() {
            
               DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            {
                Object[] row = new Object[2];
                row[0] = organization.getType().getValue();
                row[1] = organization.getName();
                model.addRow(row);
            }

        }
            
        }
    
    private void populateOrganizationTypeComboBox() {
        cbOrganization.removeAllItems();
        cbOrganization.addItem(Organization.OrganizationType.HouseLessorOrganization);
    

    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOrganizationName = new javax.swing.JLabel();
        lblOrganizationType = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();
        btnAddOrganization = new javax.swing.JButton();
        cbOrganization = new javax.swing.JComboBox();
        splitpaneTable = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblTitle.setText("Manage Rental Enterprise Organizations");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        lblOrganizationName.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblOrganizationName.setText("Organization Name:");
        add(lblOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        lblOrganizationType.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblOrganizationType.setText("Organization Type:");
        add(lblOrganizationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        txtOrganizationName.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        add(txtOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 170, 30));

        btnAddOrganization.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnAddOrganization.setText("Add Organization");
        btnAddOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganizationActionPerformed(evt);
            }
        });
        add(btnAddOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 140, -1));

        cbOrganization.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        cbOrganization.setForeground(new java.awt.Color(25, 56, 82));
        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item1", "Item2" }));
        cbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrganizationActionPerformed(evt);
            }
        });
        add(cbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 170, 30));

        tblOrganization.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Type", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        splitpaneTable.setViewportView(tblOrganization);

        add(splitpaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 520, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void cbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrganizationActionPerformed
        // TODO add your handling code here:
//        Organization org = (Organization) cbOrganization.getSelectedItem();
//        if (org != null) {
//            popRoleComboBox(org);
//        }
    }//GEN-LAST:event_cbOrganizationActionPerformed

    private void btnAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganizationActionPerformed
        // TODO add your handling code here:
        Organization.OrganizationType type = (Organization.OrganizationType) cbOrganization.getSelectedItem();

        if ("".equals(txtOrganizationName.getText())) {
            JOptionPane.showMessageDialog(null, "Enter organization name!");
        } else {
            Organization organization = directory.createOrganization(type, txtOrganizationName.getText());
            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
            txtOrganizationName.setText("");
            volPopulate();
        }
        
    }//GEN-LAST:event_btnAddOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrganization;
    private javax.swing.JComboBox cbOrganization;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane splitpaneTable;
    private javax.swing.JTable tblOrganization;
    private javax.swing.JTextField txtOrganizationName;
    // End of variables declaration//GEN-END:variables
}
