/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HouseLessorRole;

import Business.EcoSystem;
import Business.House.House;
import Business.HouseLessor.HouseLessor;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shiva
 */
public class ManageHouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHouseJPanel
     */
     JPanel userProcessContainer;    
    public EcoSystem system;
    public HouseLessor currentHouseLessor;
    public Organization Organization;
    public String role;
    public UserAccount account;
    
    public ManageHouseJPanel(JPanel userProcessContainer,UserAccount account, HouseLessor currentHouseLessor,Organization organization,String Role, EcoSystem system) {
        initComponents();
          this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.currentHouseLessor = currentHouseLessor;
        this.Organization = organization;
        this.role = Role;
        this.account = account;
        PopulateHouses();
    }
    
    public void PopulateHouses(){
        DefaultTableModel model = (DefaultTableModel) tblHouseList.getModel();

        model.setRowCount(0);
        for(House h: this.system.getHouseDirectory().getHouseList()){
            if(h.getHouseLessor().Name.equals(this.currentHouseLessor.getName()));
            Object[] row = new Object[4];
                row[0] = h.getId();
                row[1] = h.getHouseName();
                row[2] = h.getAddress();
                row[3] = h.getCity();
                model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHouseList = new javax.swing.JTable();
        labladd = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        AddHouse = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHeading.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelHeading.setText("THe FOLLOWING ARE THE HOUSES OWNED BY YOU.");
        add(labelHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 390, 40));

        tblHouseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "City", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHouseList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 620, 230));

        labladd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labladd.setText("ADD A House ");
        add(labladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 120, 30));

        lblAddress.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblAddress.setText("Address:");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 80, 30));

        lblName1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblName1.setText("Name:");
        add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 80, 30));

        lblCity.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 80, 30));

        txtAddress.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 140, 30));

        txtName.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 30));

        txtCity1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        add(txtCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 140, 30));

        AddHouse.setText("Add");
        AddHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddHouseActionPerformed(evt);
            }
        });
        add(AddHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 140, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddHouseActionPerformed
        // TODO add your handling code here:
        
        
        if(txtName.getText()!= null)
        {
            String Name=null;
        String Address=null;
        String City=null;
        if(txtName.getText() != "")
            Name= txtName.getText();
        
        if(txtAddress.getText()!= ""){
            Address = txtAddress.getText();
        }
        
        if(txtCity1.getText()!= null)
            City = txtCity1.getText();
        
        House newHouse = system.getHouseDirectory().CreateHouse(Name, City, Address);
        newHouse.setHouseLessor(currentHouseLessor);
        JOptionPane.showMessageDialog(null, "House Added Successfully");
        PopulateHouses();
        txtName.setText("");
        txtAddress.setText("");
        txtCity1.setText("");
        }
        else{
             JOptionPane.showMessageDialog(null, "Please Enter Value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_AddHouseActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHouseList.getSelectedRow();
        
        if(selectedRow >= 0){
            DefaultTableModel tableRecords = (DefaultTableModel)tblHouseList.getModel();
            int id = (int)tableRecords.getValueAt(selectedRow, 0);
            House h = system.houseDirectory.getHouseById(id);
            system.houseDirectory.HouseList.remove(h);
            JOptionPane.showMessageDialog(null, "House deleted Successfully");
            PopulateHouses();
        }
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddHouse;
    private javax.swing.JButton Delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JLabel labladd;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTable tblHouseList;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
