/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterParentRole;

import Business.EcoSystem;
import javax.swing.JPanel;

/**
 *
 * @author Deepika Reddy
 */
public class FosterAChild extends javax.swing.JPanel {

    /**
     * Creates new form FosterAChild
     */
    JPanel userProcessContainer;    
    public EcoSystem system;
    
    public FosterAChild(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollpaneFosterChild = new javax.swing.JScrollPane();
        tblFosterChild = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("List Of Children Available");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        tblFosterChild.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Age", "Place Of Origin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneFosterChild.setViewportView(tblFosterChild);

        add(scrollpaneFosterChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 520, 170));

        btnSelect.setText("Select Foster Child");
        add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollpaneFosterChild;
    private javax.swing.JTable tblFosterChild;
    // End of variables declaration//GEN-END:variables
}
