/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterChildRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.FosterChild.FosterChild;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnrollforCounselingWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shiva
 */
public class ChildCounsellingHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChildCounsellingHistoryJPanel
     */
    
    
    
    
    JPanel userProcessContainer;  
    public EcoSystem system;
    public FosterChild CurrentChild;
    public UserAccount account;
    public Enterprise Enterprise;
    public Network network;
    
    
    public ChildCounsellingHistoryJPanel(JPanel userProcessContainer,UserAccount account, FosterChild CurrentChild, Network network, Enterprise enterprise, EcoSystem system) {
        
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.CurrentChild = CurrentChild;
        this.Enterprise = enterprise;
        this.account = account;
        this.network = network;
        populateTable();
        
    }
    
    
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblCounsHostory.getModel();
        model.setRowCount(0);
        for(WorkRequest wq: this.system.getWorkQueue().getWorkRequestList()){
            if(wq.getClass() == EnrollforCounselingWorkRequest.class){
                Object[] row = new Object[model.getColumnCount()];
                EnrollforCounselingWorkRequest facwq = (EnrollforCounselingWorkRequest)wq;
                if(facwq.getFosterChild().getName().equals(this.CurrentChild.getName())){
                    row[0] = facwq.getReqId();
                    row[1] = facwq.getChildCounselor().getName();
                    row[2] = facwq.getStatus();
                   ((DefaultTableModel) tblCounsHostory.getModel()).addRow(row);
                }
                
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCounsHostory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 229, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("THE COUNSELLING HISTORY IS AS FOLLOWS.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 351, 29));

        tblCounsHostory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Counsellor", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCounsHostory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 589, 119));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SysAdminRole/children.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 269, -1, 260));
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCounsHostory;
    // End of variables declaration//GEN-END:variables
}
