/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterChildRole;

import Business.ChildCounsellor.ChildCounsellor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.FosterChild.FosterChild;
import Business.Instructor.Instructor;
import Business.Network.Network;
import Business.Parent.Parent;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnrollforCounselingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shiva
 */
public class FosterChildCounselingSlotJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FosterChildCounselingSlotJPanel
     */
    JPanel userProcessContainer;  
    public EcoSystem system;
    public FosterChild CurrentChild;
    public UserAccount account;
    public Enterprise Enterprise;
    public Network network;
    public FosterChildCounselingSlotJPanel(JPanel userProcessContainer,UserAccount account, FosterChild CurrentChild, Network network, Enterprise enterprise, EcoSystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.CurrentChild = CurrentChild;
        this.Enterprise = enterprise;
        this.account = account;
        this.network = network;
        populateTable();
        
    }
    
     private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblCounselors.getModel();
        model.setRowCount(0);
        
        for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
            
            if(enterprise.getEnterpriseType().toString().equals("Training Center")){
                for(ChildCounsellor ins: enterprise.getChildCounsellorDirectory().ChildCounsellorList){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0]= ins;
                row[1] = ins.getChildCounsellorId();
                row[2] = ins.getName();
                row[3] = ins.getPhoneNumber();
                row[4] = ins.getAddress();
               ((DefaultTableModel) tblCounselors.getModel()).addRow(row);
                }
            } 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneInstructor = new javax.swing.JScrollPane();
        tblCounselors = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 229, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCounselors.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        tblCounselors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Counselor", "Counselor ID", "Name", "Phone", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneInstructor.setViewportView(tblCounselors);

        add(scrollpaneInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 510, 110));

        lblTitle.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblTitle.setText("List of Counselors");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        btnEnroll.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        Back.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SysAdminRole/children.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblCounselors.getSelectedRow();

        if(selectedRow >=0){
            DefaultTableModel tableRecords = (DefaultTableModel)tblCounselors.getModel();
            ChildCounsellor couns = (ChildCounsellor)tableRecords.getValueAt(selectedRow, 0);

            EnrollforCounselingWorkRequest enrolReq = new EnrollforCounselingWorkRequest();
            enrolReq.setEnterprise(Enterprise);
            enrolReq.setNetwork(network);
            enrolReq.setFosterChild(CurrentChild);
            enrolReq.setChildCounselor(couns);
            enrolReq.setStatus("Training Enroll requested.");
            enrolReq.setReqId(system.getWorkQueue().getWorkRequestList().size()+1);

            system.getWorkQueue().getWorkRequestList().add(enrolReq);

            JOptionPane.showMessageDialog(null, " Training Enrolled Requested.");

        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FosterChildWorkAreaJPanel sysAdminwjp = (FosterChildWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollpaneInstructor;
    private javax.swing.JTable tblCounselors;
    // End of variables declaration//GEN-END:variables
}
