/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoVolunteerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Voluteers.Volunteer;
import Business.WorkQueue.NGOContributeWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shiva
 */
public class ContributeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContributeJPanel
     */
   JPanel userProcessContainer;    
    public EcoSystem system;
    public Volunteer CurrentVolunteer;
    public Organization Organization;
    public String role;
    public UserAccount account;
    public Enterprise enterprise;
    public Network network;
    
    public ContributeJPanel(JPanel userProcessContainer,UserAccount account, Volunteer CurrentVolunteer,Network network,Enterprise enterprise,Organization organization,String Role, EcoSystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.CurrentVolunteer = CurrentVolunteer;
        this.Organization = organization;
        this.role = Role;
        this.account = account;
        this.enterprise = enterprise;
        this.network = network;
        //this.PopulateWidgets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblamount1 = new javax.swing.JLabel();
        btnContribute = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 229, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel1.setText("Contribute");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 41, 115, 42));

        lblamount1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lblamount1.setText("Please Enter the amount of money you are Interested To Contribute:");
        add(lblamount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 178, -1, 38));

        btnContribute.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        btnContribute.setText("Contribute");
        btnContribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContributeActionPerformed(evt);
            }
        });
        add(btnContribute, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 289, 166, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SysAdminRole/donate.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 740, 410));
        add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContributeActionPerformed
        // TODO add your handling code here:
        String a = txtamount.getText();
        int amount;
        try{
            amount = Integer.parseInt(a);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numeric values only.");
            return;
        }
        
        
        
        NGOContributeWorkRequest wq = new NGOContributeWorkRequest(CurrentVolunteer, network, Organization, enterprise,amount);
        wq.setStatus("Contribution Requested.");
        wq.setReqId(this.system.getWorkQueue().getWorkRequestList().size() +1);
        this.system.getWorkQueue().getWorkRequestList().add(wq);
        JOptionPane.showMessageDialog(null, "Contribution requested.");
    }//GEN-LAST:event_btnContributeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContribute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblamount1;
    private javax.swing.JTextField txtamount;
    // End of variables declaration//GEN-END:variables
}
