/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CounsellorRole;

import Business.ChildCounsellor.ChildCounsellor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.HouseLessorRole.HouseLessorViewProfileJPanel;
import userinterface.SysAdminRole.ManageWorkRequestJPanel;

/**
 *
 * @author shiva
 */
public class CounsellorRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CounsellorRoleWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;
        public ChildCounsellor currentChildCounsellor;

    Organization organization;
    public CounsellorRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.network = network;
        this.enterprise = enterprise;
        this.organization = organization;
        this.ComputeCurrentChildCounsellor();
         labelheading.setText("Hello "+ this.currentChildCounsellor.getName());
        
    }
    public void ComputeCurrentChildCounsellor(){
        String name = this.account.getEmployee().getName();
        
        this.currentChildCounsellor = this.enterprise.getChildCounsellorDirectory().getChildCounsellorByName(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewProfile = new javax.swing.JButton();
        btnManageWorkRequest = new javax.swing.JButton();
        labelheading = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        add(btnViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        btnManageWorkRequest.setText("Manage Work Request");
        btnManageWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWorkRequestActionPerformed(evt);
            }
        });
        add(btnManageWorkRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        labelheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelheading.setText("Hello<counsellor name>");
        add(labelheading, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
          CounsellorViewProfileJPanel viewProfile = new CounsellorViewProfileJPanel(userProcessContainer, account, currentChildCounsellor, organization,account.getRole().toString(), system);
        userProcessContainer.add("CounsellorViewProfileJPanel",viewProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnManageWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWorkRequestActionPerformed
        // TODO add your handling code here:
         CounsellorManageWorkReqJPanel viewProfile = new CounsellorManageWorkReqJPanel(userProcessContainer, account, currentChildCounsellor, organization,account.getRole().toString(), system);
        userProcessContainer.add("CounsellorViewProfileJPanel",viewProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageWorkRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageWorkRequest;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel labelheading;
    // End of variables declaration//GEN-END:variables
}
